config/routes.rb
Photobooth::Application.routes.draw do
  resources :users

  root 'photo_session#photobooth'

  get 'participant/:id' => 'participant#create'

    resources :photo_session

end

app/models/participant.rb
class Participant < ActiveRecord::Base
    belongs_to :photo_session

    validates :name, presence: true,
                   length: {in: 1..70,}

    validates :email, uniqueness: true, length: {in: 1..70,}
end

app/models/photo.rb
class Photo < ActiveRecord::Base
end

app/models/photo_session.rb
class PhotoSession < ActiveRecord::Base
  has_many :photos
  has_many :participant
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :photo_session

  validates :name, presence: true,
                 length: {in: 1..70,}

  validates :email, uniqueness: true, length: {in: 1..70,}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/participant_controller.rb
class ParticipantController < ApplicationController

  skip_before_filter :verify_authenticity_token


  def index
    @participants = Participant.all
  end

  def new
    @participant = Participant.new
  end


  def create
    @participant1 = Participant.new
    @participant1.name = params[:name1]
    @participant1.email = params[:emai1]
    @participant1.save

    render "photo_session#photobooth"
    #redirect_to :back
  end


  def show
    @participant = Participant.find(params[:id])
  end

  #private
  #def participant_params
  #  params.require(:participant).permit(:name, :email, :photo_session_id)
  #end


end

app/controllers/photo_session_controller.rb
class PhotoSessionController < ApplicationController

  skip_before_filter :verify_authenticity_token

  def index
    @PhotoSessions = PhotoSession.all
    @photo = Photo.all
  end

  def show
    @PhotoSessions = PhotoSession.all
    @photo = Photo.all
  end

  def photobooth
  end

  def new
    @PhotoSessions = PhotoSession.new
  end

  def create
    @PhotoSessions = PhotoSession.new
    @PhotoSessions.save

    @photo1 = Photo.new
    @photo1.image_data = params[:mydata1]
    @photo1.photo_session_id = @PhotoSessions.id
    @photo1.save

    @photo2 = Photo.new
    @photo2.image_data = params[:mydata2]
    @photo2.photo_session_id = @PhotoSessions.id
    @photo2.save

    @photo3 = Photo.new
    @photo3.image_data = params[:mydata3]
    @photo3.photo_session_id = @PhotoSessions.id
    @photo3.save

   redirect_to :back
    #redirect_to  "/participant/" + @PhotoSessions.idS
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/participant_helper.rb
module ParticipantHelper
end

app/helpers/photo_session_helper.rb
module PhotoSessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photobooth</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/participant/create.html.erb
  <body>
    <header>
      <h1> Baby Brennan </h1>
      <h2> Est. Oct </h2>
    </header>
    <section>
      <form id="formbackground" method="post" action="participant">
      </form>
    </section>
    <section class="buttonbackground">
      <button type="button" id="addButton" name="Add"> Add Person </button>
      <button id="submit" name="submit"> Submit </button>
      <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
  </section>
</html>

app/views/participant/index.html.erb
<h1>participants</h1>

<% @participants.each do |p| %>
  <%= p.name %>
  <%= p.email %>
<% end %>

app/views/participant/new.html.erb
<%= form_for :participant, url: participant_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :photo_session_id %><br>
    <%= f.text_field :photo_session_id %>
  </p>

  <p>
    <%= f.submit "add person" %>
  </p>
<% end %>

app/views/participant/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @participant.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @participant.email %>
</p>

app/views/photo_session/index.html.erb
<title> Amber and Al </title>
<link href='http://fonts.googleapis.com/css?family=Dancing+Script' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="style.css"></link>
</head>
<body>
  <header>
    <h1> Baby Brennan </h1>
    <h2> Est. Oct 2015 </h2>
  </header>

<h3><%= link_to "Take Photo", root_path, :class => "link" %></h3>

<% @photo.reverse_each do |photo| %>
  <img class="photogallery" src='data:image/jpeg;base64,<%=  photo.image_data %>'/>
<% end %>

<div class='hide'>
  <div id="my_camera" style="width:320px; height:240px;"></div>
</div>
</body>

app/views/photo_session/photobooth.html.erb

<html>
  <head>
    <title> Amber and Al </title>
    <link href='http://fonts.googleapis.com/css?family=Dancing+Script' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="style.css"></link>
  </head>
  <body id="body">
    <header>
      <h1> Baby Brennan </h1>
      <h2> Est. Oct 2015 </h2>
    </header>

    <div class="linkdiv">
      <%= link_to "View all Photos", photo_session_index_path, :class=> "link" %>
    </div>

    <div class="loader">
      <center>
       <img class="loading-image" src="assets/loading.jpg" alt="loading..">
     </center>
   </div>

    <section class="primary">
      <button id="start" class="show"> Start </button>
      <div id="countDiv" class="hide"></div>
    </section>

    <section class="secondary">
      <div id="my_camera" style="width:320px; height:240px;"></div>
      <div id="my_result1"></div>
      <div id="my_result2"></div>
      <div id="my_result3"></div>

      <form id="myform" method="post" action="photo_session">
        <input id="mydata1" type="hidden" name="mydata1" value=""/>
        <input id="mydata2" type="hidden" name="mydata2" value=""/>
        <input id="mydata3" type="hidden" name="mydata3" value=""/>
      </form>
    </section>
    <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
  </body>
</html>

app/views/photo_session/show.html.erb
<title> Amber and Al </title>
<link href='http://fonts.googleapis.com/css?family=Dancing+Script' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="style.css"></link>
</head>
<body>
  <header>
    <h1> Baby Brennan </h1>
    <h2> Est. Oct 2015 </h2>
  </header>

  <h3><%= link_to "Take Photo", root_path, :class=> "link" %></h3>

  <% @photo.reverse_each do |photo| %>
    <img class="photogallery" src='data:image/jpeg;base64,<%=  photo.image_data %>'/>
  <% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>